name: "Common Steps"
description: "Common steps for dev and prod jobs"
inputs:
  environment:
    description: "The environment for the job"
    required: true
runs:
  using: "composite"
  steps:
    - name: Print Env
      run: echo "Environment - ${{ inputs.environment }}"

    - name: Run a script
      run: echo "Running job in ${{ inputs.environment }} environment"
