name: Actions Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/actions-workflow.yaml'
      - '.github/actions/common-steps'

jobs:
  dev-job:
    name: Development Job
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run common steps for dev
      uses: ./.github/actions/common-steps
      with:
        environment: dev

  prod-job:
    name: Production Job
    runs-on: ubuntu-latest
    needs: dev-job
    environment: prod
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run common steps for prod
      uses: ./.github/actions/common-steps
      with:
        environment: prod
