name: Environments Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/environments-workflow.yaml'

jobs:
  dev-job:
    name: Development Job
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script for development
        run: echo "Running development job"

  prod-job:
    name: Production Job
    runs-on: ubuntu-latest
    needs: dev-job
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script for production
        run: echo "Running production job"
