name: Secret Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/secret-workflow.yaml'

jobs:
  secret-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Broadcast Secret
      run: |
        echo ${{ secrets.MESSAGE }}
