name: Deployment Workflow (Shared)

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to display'
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dev-job:
    name: Development Job
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run common steps for dev
      uses: ./.github/actions/common-steps
      with:
        environment: dev

    - name: Hello World
      run: |
        echo "Hello World"
        echo "Secret: ${{ secrets.token }}"

  prod-job:
    name: Production Job
    runs-on: ubuntu-latest
    needs: dev-job
    environment: prod
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run common steps for prod
      uses: ./.github/actions/common-steps
      with:
        environment: prod

    - name: Hello World
      run: |
        echo "Hello World"
        echo "Secret: ${{ secrets.token }}"
