name: Shared Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/shared-workflow.yaml'
      - '.github/workflows/shared-deployment-workflow.yaml'

jobs:
  deployment:
    name: Run deployment
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      message: "Hello World"
    secrets:
      token: ${{ secrets.TOKEN }}
