name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/simple-workflow.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Broadcast Message
      run: |
        echo "Hello World"
